[ReleaseNote.Maker]
Directory = "ChangeLog.d"
OutputFileName = "CHANGELOG.md"
TemplateFilePath = "ChangeLog.d/Template.t4"
CsprojPath = "NF.Tool.ReleaseNoteMaker/NF.Tool.ReleaseNoteMaker.CLI/NF.Tool.ReleaseNoteMaker.CLI.csproj"
EndOfLine = "LF"
StartString = "<!-- release notes start -->\n"
IssueFormat = "[{Issue}](https://github.com/netpyoung/NF.Tool.ReleaseNoteMaker/issues/{Issue})"

[[ReleaseNote.Section]]
Path = ""
DisplayName = "Main"

[[ReleaseNote.Type]]
Category = "security"
DisplayName = "Security"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "removed"
DisplayName = "Removed"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "deprecated"
DisplayName = "Deprecated"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "added"
DisplayName = "Added"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "changed"
DisplayName = "Changed"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "fixed"
DisplayName = "Fixed"
IsShowContent = true

[[ReleaseNote.Type]]
Category = "feature"
DisplayName = "Features"
IsShowContent = true
